name: Deploy
on:
  push:
    branches:
      - main
concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      github.repository_owner == 'bunui-kit' &&
      !startsWith(github.event.head_commit.message, 'chore(release)')
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: false

      - name: Add remote host to known_hosts
        run: "ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts"

      - name: Deploy to VPS
        run:
          ssh ${{secrets.USERNAME}}@${{secrets.HOST}}
          "./deploy/deploy-bun-ui.sh"
